services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jogoteca
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app

volumes:
  db_data:
